"use client"

import { useState } from "react"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

interface AddressSuggestion {
  place_id: string
  description: string
  structured_formatting: {
    main_text: string
    secondary_text: string
  }
}

interface AddressAutocompleteProps {
  id: string
  label: string
  placeholder: string
  value: string
  onChange: (value: string) => void
  icon: "from" | "to"
  className?: string
}

const indiaLocations = [
  // Major Metropolitan Cities
  { main: "Mumbai", secondary: "Maharashtra, India" },
  { main: "Delhi", secondary: "Delhi, India" },
  { main: "Bangalore", secondary: "Karnataka, India" },
  { main: "Hyderabad", secondary: "Telangana, India" },
  { main: "Chennai", secondary: "Tamil Nadu, India" },
  { main: "Kolkata", secondary: "West Bengal, India" },
  { main: "Pune", secondary: "Maharashtra, India" },
  { main: "Ahmedabad", secondary: "Gujarat, India" },
  { main: "Jaipur", secondary: "Rajasthan, India" },
  { main: "Surat", secondary: "Gujarat, India" },
  { main: "Lucknow", secondary: "Uttar Pradesh, India" },
  { main: "Kanpur", secondary: "Uttar Pradesh, India" },
  { main: "Nagpur", secondary: "Maharashtra, India" },
  { main: "Indore", secondary: "Madhya Pradesh, India" },
  { main: "Thane", secondary: "Maharashtra, India" },
  { main: "Bhopal", secondary: "Madhya Pradesh, India" },
  { main: "Visakhapatnam", secondary: "Andhra Pradesh, India" },
  { main: "Pimpri-Chinchwad", secondary: "Maharashtra, India" },
  { main: "Patna", secondary: "Bihar, India" },
  { main: "Vadodara", secondary: "Gujarat, India" },
  { main: "Ghaziabad", secondary: "Uttar Pradesh, India" },
  { main: "Ludhiana", secondary: "Punjab, India" },
  { main: "Agra", secondary: "Uttar Pradesh, India" },
  { main: "Nashik", secondary: "Maharashtra, India" },
  { main: "Faridabad", secondary: "Haryana, India" },
  { main: "Meerut", secondary: "Uttar Pradesh, India" },
  { main: "Rajkot", secondary: "Gujarat, India" },
  { main: "Kalyan-Dombivali", secondary: "Maharashtra, India" },
  { main: "Vasai-Virar", secondary: "Maharashtra, India" },
  { main: "Varanasi", secondary: "Uttar Pradesh, India" },
  { main: "Srinagar", secondary: "Jammu and Kashmir, India" },
  { main: "Aurangabad", secondary: "Maharashtra, India" },
  { main: "Dhanbad", secondary: "Jharkhand, India" },
  { main: "Amritsar", secondary: "Punjab, India" },
  { main: "Navi Mumbai", secondary: "Maharashtra, India" },
  { main: "Allahabad", secondary: "Uttar Pradesh, India" },
  { main: "Ranchi", secondary: "Jharkhand, India" },
  { main: "Howrah", secondary: "West Bengal, India" },
  { main: "Coimbatore", secondary: "Tamil Nadu, India" },
  { main: "Jabalpur", secondary: "Madhya Pradesh, India" },
  { main: "Gwalior", secondary: "Madhya Pradesh, India" },
  { main: "Vijayawada", secondary: "Andhra Pradesh, India" },
  { main: "Jodhpur", secondary: "Rajasthan, India" },
  { main: "Madurai", secondary: "Tamil Nadu, India" },
  { main: "Raipur", secondary: "Chhattisgarh, India" },
  { main: "Kota", secondary: "Rajasthan, India" },
  { main: "Chandigarh", secondary: "Chandigarh, India" },
  { main: "Guwahati", secondary: "Assam, India" },
  { main: "Solapur", secondary: "Maharashtra, India" },
  { main: "Hubli-Dharwad", secondary: "Karnataka, India" },
  { main: "Bareilly", secondary: "Uttar Pradesh, India" },
  { main: "Moradabad", secondary: "Uttar Pradesh, India" },
  { main: "Mysore", secondary: "Karnataka, India" },
  { main: "Gurgaon", secondary: "Haryana, India" },
  { main: "Aligarh", secondary: "Uttar Pradesh, India" },
  { main: "Jalandhar", secondary: "Punjab, India" },
  { main: "Tiruchirappalli", secondary: "Tamil Nadu, India" },
  { main: "Bhubaneswar", secondary: "Odisha, India" },
  { main: "Salem", secondary: "Tamil Nadu, India" },
  { main: "Warangal", secondary: "Telangana, India" },
  { main: "Mira-Bhayandar", secondary: "Maharashtra, India" },
  { main: "Thiruvananthapuram", secondary: "Kerala, India" },
  { main: "Bhiwandi", secondary: "Maharashtra, India" },
  { main: "Saharanpur", secondary: "Uttar Pradesh, India" },
  { main: "Guntur", secondary: "Andhra Pradesh, India" },
  { main: "Amravati", secondary: "Maharashtra, India" },
  { main: "Bikaner", secondary: "Rajasthan, India" },
  { main: "Noida", secondary: "Uttar Pradesh, India" },
  { main: "Jamshedpur", secondary: "Jharkhand, India" },
  { main: "Bhilai Nagar", secondary: "Chhattisgarh, India" },
  { main: "Cuttack", secondary: "Odisha, India" },
  { main: "Firozabad", secondary: "Uttar Pradesh, India" },
  { main: "Kochi", secondary: "Kerala, India" },
  { main: "Bhavnagar", secondary: "Gujarat, India" },
  { main: "Dehradun", secondary: "Uttarakhand, India" },
  { main: "Durgapur", secondary: "West Bengal, India" },
  { main: "Asansol", secondary: "West Bengal, India" },
  { main: "Nanded-Waghala", secondary: "Maharashtra, India" },
  { main: "Kolhapur", secondary: "Maharashtra, India" },
  { main: "Ajmer", secondary: "Rajasthan, India" },
  { main: "Gulbarga", secondary: "Karnataka, India" },
  { main: "Jamnagar", secondary: "Gujarat, India" },
  { main: "Ujjain", secondary: "Madhya Pradesh, India" },
  { main: "Loni", secondary: "Uttar Pradesh, India" },
  { main: "Siliguri", secondary: "West Bengal, India" },
  { main: "Jhansi", secondary: "Uttar Pradesh, India" },
  { main: "Ulhasnagar", secondary: "Maharashtra, India" },
  { main: "Nellore", secondary: "Andhra Pradesh, India" },
  { main: "Jammu", secondary: "Jammu and Kashmir, India" },
  { main: "Sangli-Miraj & Kupwad", secondary: "Maharashtra, India" },
  { main: "Mangalore", secondary: "Karnataka, India" },
  { main: "Erode", secondary: "Tamil Nadu, India" },
  { main: "Belgaum", secondary: "Karnataka, India" },
  { main: "Ambattur", secondary: "Tamil Nadu, India" },
  { main: "Tirunelveli", secondary: "Tamil Nadu, India" },
  { main: "Malegaon", secondary: "Maharashtra, India" },
  { main: "Gaya", secondary: "Bihar, India" },
  { main: "Jalgaon", secondary: "Maharashtra, India" },
  { main: "Udaipur", secondary: "Rajasthan, India" },
  { main: "Maheshtala", secondary: "West Bengal, India" },

  // Additional Major Cities (100+ more)
  { main: "Akola", secondary: "Maharashtra, India" },
  { main: "Latur", secondary: "Maharashtra, India" },
  { main: "Dhule", secondary: "Maharashtra, India" },
  { main: "Ahmednagar", secondary: "Maharashtra, India" },
  { main: "Chandrapur", secondary: "Maharashtra, India" },
  { main: "Parbhani", secondary: "Maharashtra, India" },
  { main: "Ichalkaranji", secondary: "Maharashtra, India" },
  { main: "Jalna", secondary: "Maharashtra, India" },
  { main: "Ambarnath", secondary: "Maharashtra, India" },
  { main: "Bhusawal", secondary: "Maharashtra, India" },
  { main: "Panvel", secondary: "Maharashtra, India" },
  { main: "Badlapur", secondary: "Maharashtra, India" },
  { main: "Beed", secondary: "Maharashtra, India" },
  { main: "Gondia", secondary: "Maharashtra, India" },
  { main: "Satara", secondary: "Maharashtra, India" },
  { main: "Barshi", secondary: "Maharashtra, India" },
  { main: "Yavatmal", secondary: "Maharashtra, India" },
  { main: "Achalpur", secondary: "Maharashtra, India" },
  { main: "Osmanabad", secondary: "Maharashtra, India" },
  { main: "Nandurbar", secondary: "Maharashtra, India" },
  { main: "Wardha", secondary: "Maharashtra, India" },
  { main: "Udgir", secondary: "Maharashtra, India" },
  { main: "Hinganghat", secondary: "Maharashtra, India" },

  // Uttar Pradesh Cities
  { main: "Gorakhpur", secondary: "Uttar Pradesh, India" },
  { main: "Mathura", secondary: "Uttar Pradesh, India" },
  { main: "Muzaffarnagar", secondary: "Uttar Pradesh, India" },
  { main: "Rampur", secondary: "Uttar Pradesh, India" },
  { main: "Shahjahanpur", secondary: "Uttar Pradesh, India" },
  { main: "Farrukhabad", secondary: "Uttar Pradesh, India" },
  { main: "Hapur", secondary: "Uttar Pradesh, India" },
  { main: "Etawah", secondary: "Uttar Pradesh, India" },
  { main: "Mirzapur", secondary: "Uttar Pradesh, India" },
  { main: "Bulandshahr", secondary: "Uttar Pradesh, India" },
  { main: "Sambhal", secondary: "Uttar Pradesh, India" },
  { main: "Amroha", secondary: "Uttar Pradesh, India" },
  { main: "Hardoi", secondary: "Uttar Pradesh, India" },
  { main: "Fatehpur", secondary: "Uttar Pradesh, India" },
  { main: "Raebareli", secondary: "Uttar Pradesh, India" },
  { main: "Orai", secondary: "Uttar Pradesh, India" },
  { main: "Sitapur", secondary: "Uttar Pradesh, India" },
  { main: "Bahraich", secondary: "Uttar Pradesh, India" },
  { main: "Modinagar", secondary: "Uttar Pradesh, India" },
  { main: "Unnao", secondary: "Uttar Pradesh, India" },
  { main: "Jaunpur", secondary: "Uttar Pradesh, India" },
  { main: "Lakhimpur", secondary: "Uttar Pradesh, India" },
  { main: "Hathras", secondary: "Uttar Pradesh, India" },
  { main: "Banda", secondary: "Uttar Pradesh, India" },

  // Gujarat Cities
  { main: "Anand", secondary: "Gujarat, India" },
  { main: "Morbi", secondary: "Gujarat, India" },
  { main: "Mahesana", secondary: "Gujarat, India" },
  { main: "Bharuch", secondary: "Gujarat, India" },
  { main: "Vapi", secondary: "Gujarat, India" },
  { main: "Navsari", secondary: "Gujarat, India" },
  { main: "Veraval", secondary: "Gujarat, India" },
  { main: "Porbandar", secondary: "Gujarat, India" },
  { main: "Godhra", secondary: "Gujarat, India" },
  { main: "Botad", secondary: "Gujarat, India" },
  { main: "Palanpur", secondary: "Gujarat, India" },
  { main: "Patan", secondary: "Gujarat, India" },
  { main: "Surendranagar", secondary: "Gujarat, India" },
  { main: "Bhuj", secondary: "Gujarat, India" },
  { main: "Gandhidham", secondary: "Gujarat, India" },
  { main: "Nadiad", secondary: "Gujarat, India" },
  { main: "Junagadh", secondary: "Gujarat, India" },
  { main: "Unjha", secondary: "Gujarat, India" },
  { main: "Gondal", secondary: "Gujarat, India" },
  { main: "Dahod", secondary: "Gujarat, India" },
  { main: "Jetpur", secondary: "Gujarat, India" },
  { main: "Kalol", secondary: "Gujarat, India" },
  { main: "Mehsana", secondary: "Gujarat, India" },
  { main: "Modasa", secondary: "Gujarat, India" },

  // Rajasthan Cities
  { main: "Alwar", secondary: "Rajasthan, India" },
  { main: "Bharatpur", secondary: "Rajasthan, India" },
  { main: "Sikar", secondary: "Rajasthan, India" },
  { main: "Bhilwara", secondary: "Rajasthan, India" },
  { main: "Tonk", secondary: "Rajasthan, India" },
  { main: "Kishangarh", secondary: "Rajasthan, India" },
  { main: "Beawar", secondary: "Rajasthan, India" },
  { main: "Hanumangarh", secondary: "Rajasthan, India" },
  { main: "Ganganagar", secondary: "Rajasthan, India" },
  { main: "Churu", secondary: "Rajasthan, India" },
  { main: "Jhunjhunu", secondary: "Rajasthan, India" },
  { main: "Pali", secondary: "Rajasthan, India" },
  { main: "Barmer", secondary: "Rajasthan, India" },
  { main: "Jaisalmer", secondary: "Rajasthan, India" },
  { main: "Jodhpur", secondary: "Rajasthan, India" },
  { main: "Nagaur", secondary: "Rajasthan, India" },
  { main: "Makrana", secondary: "Rajasthan, India" },
  { main: "Sujangarh", secondary: "Rajasthan, India" },
  { main: "Ladnu", secondary: "Rajasthan, India" },
  { main: "Didwana", secondary: "Rajasthan, India" },
  { main: "Ratangarh", secondary: "Rajasthan, India" },
  { main: "Sardarshahar", secondary: "Rajasthan, India" },
  { main: "Taranagar", secondary: "Rajasthan, India" },
  { main: "Chhabra", secondary: "Rajasthan, India" },

  // Karnataka Cities
  { main: "Tumkur", secondary: "Karnataka, India" },
  { main: "Bellary", secondary: "Karnataka, India" },
  { main: "Bijapur", secondary: "Karnataka, India" },
  { main: "Shimoga", secondary: "Karnataka, India" },
  { main: "Raichur", secondary: "Karnataka, India" },
  { main: "Bidar", secondary: "Karnataka, India" },
  { main: "Hospet", secondary: "Karnataka, India" },
  { main: "Gadag-Betageri", secondary: "Karnataka, India" },
  { main: "Davangere", secondary: "Karnataka, India" },
  { main: "Chitradurga", secondary: "Karnataka, India" },
  { main: "Kolar", secondary: "Karnataka, India" },
  { main: "Mandya", secondary: "Karnataka, India" },
  { main: "Hassan", secondary: "Karnataka, India" },
  { main: "Udupi", secondary: "Karnataka, India" },
  { main: "Karwar", secondary: "Karnataka, India" },
  { main: "Ranebennuru", secondary: "Karnataka, India" },
  { main: "Gangavati", secondary: "Karnataka, India" },
  { main: "Bagalkot", secondary: "Karnataka, India" },
  { main: "Robertsonpet", secondary: "Karnataka, India" },
  { main: "Bhadravati", secondary: "Karnataka, India" },
  { main: "Chikmagalur", secondary: "Karnataka, India" },
  { main: "Koppal", secondary: "Karnataka, India" },
  { main: "Mundargi", secondary: "Karnataka, India" },
  { main: "Harihar", secondary: "Karnataka, India" },

  // Tamil Nadu Cities
  { main: "Vellore", secondary: "Tamil Nadu, India" },
  { main: "Thoothukudi", secondary: "Tamil Nadu, India" },
  { main: "Nagercoil", secondary: "Tamil Nadu, India" },
  { main: "Thanjavur", secondary: "Tamil Nadu, India" },
  { main: "Dindigul", secondary: "Tamil Nadu, India" },
  { main: "Cuddalore", secondary: "Tamil Nadu, India" },
  { main: "Kanchipuram", secondary: "Tamil Nadu, India" },
  { main: "Karur", secondary: "Tamil Nadu, India" },
  { main: "Neyveli", secondary: "Tamil Nadu, India" },
  { main: "Sivakasi", secondary: "Tamil Nadu, India" },
  { main: "Vellore", secondary: "Tamil Nadu, India" },
  { main: "Kumbakonam", secondary: "Tamil Nadu, India" },
  { main: "Tirupur", secondary: "Tamil Nadu, India" },
  { main: "Avadi", secondary: "Tamil Nadu, India" },
  { main: "Tambaram", secondary: "Tamil Nadu, India" },
  { main: "Alandur", secondary: "Tamil Nadu, India" },
  { main: "Pallavaram", secondary: "Tamil Nadu, India" },
  { main: "Tiruvannamalai", secondary: "Tamil Nadu, India" },
  { main: "Pudukkottai", secondary: "Tamil Nadu, India" },
  { main: "Vaniyambadi", secondary: "Tamil Nadu, India" },
  { main: "Ambur", secondary: "Tamil Nadu, India" },
  { main: "Nagapattinam", secondary: "Tamil Nadu, India" },
  { main: "Viruthunagar", secondary: "Tamil Nadu, India" },
  { main: "Pollachi", secondary: "Tamil Nadu, India" },

  // Kerala Cities
  { main: "Kozhikode", secondary: "Kerala, India" },
  { main: "Kollam", secondary: "Kerala, India" },
  { main: "Thrissur", secondary: "Kerala, India" },
  { main: "Alappuzha", secondary: "Kerala, India" },
  { main: "Kottayam", secondary: "Kerala, India" },
  { main: "Palakkad", secondary: "Kerala, India" },
  { main: "Manjeri", secondary: "Kerala, India" },
  { main: "Thalassery", secondary: "Kerala, India" },
  { main: "Ponnani", secondary: "Kerala, India" },
  { main: "Vatakara", secondary: "Kerala, India" },
  { main: "Kanhangad", secondary: "Kerala, India" },
  { main: "Payyanur", secondary: "Kerala, India" },
  { main: "Koyilandy", secondary: "Kerala, India" },
  { main: "Parappanangadi", secondary: "Kerala, India" },
  { main: "Kalamassery", secondary: "Kerala, India" },
  { main: "Neyyattinkara", secondary: "Kerala, India" },
  { main: "Kayamkulam", secondary: "Kerala, India" },
  { main: "Nedumangad", secondary: "Kerala, India" },
  { main: "Kannur", secondary: "Kerala, India" },
  { main: "Tirur", secondary: "Kerala, India" },
  { main: "Kottakkal", secondary: "Kerala, India" },
  { main: "Kasaragod", secondary: "Kerala, India" },
  { main: "Kunnamkulam", secondary: "Kerala, India" },
  { main: "Ottappalam", secondary: "Kerala, India" },

  // Andhra Pradesh & Telangana Cities
  { main: "Tirupati", secondary: "Andhra Pradesh, India" },
  { main: "Anantapur", secondary: "Andhra Pradesh, India" },
  { main: "Chittoor", secondary: "Andhra Pradesh, India" },
  { main: "Kakinada", secondary: "Andhra Pradesh, India" },
  { main: "Rajahmundry", secondary: "Andhra Pradesh, India" },
  { main: "Kadapa", secondary: "Andhra Pradesh, India" },
  { main: "Nizamabad", secondary: "Telangana, India" },
  { main: "Khammam", secondary: "Telangana, India" },
  { main: "Karimnagar", secondary: "Telangana, India" },
  { main: "Ramagundam", secondary: "Telangana, India" },
  { main: "Mahbubnagar", secondary: "Telangana, India" },
  { main: "Nalgonda", secondary: "Telangana, India" },
  { main: "Adilabad", secondary: "Telangana, India" },
  { main: "Suryapet", secondary: "Telangana, India" },
  { main: "Miryalaguda", secondary: "Telangana, India" },
  { main: "Jagtial", secondary: "Telangana, India" },
  { main: "Mancherial", secondary: "Telangana, India" },
  { main: "Siddipet", secondary: "Telangana, India" },
  { main: "Wanaparthy", secondary: "Telangana, India" },
  { main: "Kothagudem", secondary: "Telangana, India" },
  { main: "Bodhan", secondary: "Telangana, India" },
  { main: "Sangareddy", secondary: "Telangana, India" },
  { main: "Metpally", secondary: "Telangana, India" },
  { main: "Zahirabad", secondary: "Telangana, India" },

  // Mumbai Areas (Expanded)
  { main: "Andheri West", secondary: "Mumbai, Maharashtra, India" },
  { main: "Andheri East", secondary: "Mumbai, Maharashtra, India" },
  { main: "Bandra West", secondary: "Mumbai, Maharashtra, India" },
  { main: "Bandra East", secondary: "Mumbai, Maharashtra, India" },
  { main: "Juhu", secondary: "Mumbai, Maharashtra, India" },
  { main: "Powai", secondary: "Mumbai, Maharashtra, India" },
  { main: "Malad West", secondary: "Mumbai, Maharashtra, India" },
  { main: "Malad East", secondary: "Mumbai, Maharashtra, India" },
  { main: "Borivali West", secondary: "Mumbai, Maharashtra, India" },
  { main: "Borivali East", secondary: "Mumbai, Maharashtra, India" },
  { main: "Kandivali West", secondary: "Mumbai, Maharashtra, India" },
  { main: "Kandivali East", secondary: "Mumbai, Maharashtra, India" },
  { main: "Goregaon West", secondary: "Mumbai, Maharashtra, India" },
  { main: "Goregaon East", secondary: "Mumbai, Maharashtra, India" },
  { main: "Versova", secondary: "Mumbai, Maharashtra, India" },
  { main: "Lokhandwala", secondary: "Mumbai, Maharashtra, India" },
  { main: "Oshiwara", secondary: "Mumbai, Maharashtra, India" },
  { main: "Jogeshwari West", secondary: "Mumbai, Maharashtra, India" },
  { main: "Jogeshwari East", secondary: "Mumbai, Maharashtra, India" },
  { main: "Vile Parle West", secondary: "Mumbai, Maharashtra, India" },
  { main: "Vile Parle East", secondary: "Mumbai, Maharashtra, India" },
  { main: "Santacruz West", secondary: "Mumbai, Maharashtra, India" },
  { main: "Santacruz East", secondary: "Mumbai, Maharashtra, India" },
  { main: "Khar West", secondary: "Mumbai, Maharashtra, India" },
  { main: "Khar East", secondary: "Mumbai, Maharashtra, India" },
  { main: "Linking Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Hill Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Carter Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Bandra Kurla Complex", secondary: "Mumbai, Maharashtra, India" },
  { main: "Lower Parel", secondary: "Mumbai, Maharashtra, India" },
  { main: "Worli", secondary: "Mumbai, Maharashtra, India" },
  { main: "Prabhadevi", secondary: "Mumbai, Maharashtra, India" },
  { main: "Dadar West", secondary: "Mumbai, Maharashtra, India" },
  { main: "Dadar East", secondary: "Mumbai, Maharashtra, India" },
  { main: "Matunga West", secondary: "Mumbai, Maharashtra, India" },
  { main: "Matunga East", secondary: "Mumbai, Maharashtra, India" },
  { main: "Mahim", secondary: "Mumbai, Maharashtra, India" },
  { main: "Wadala", secondary: "Mumbai, Maharashtra, India" },
  { main: "King Circle", secondary: "Mumbai, Maharashtra, India" },
  { main: "Sion", secondary: "Mumbai, Maharashtra, India" },
  { main: "Kurla West", secondary: "Mumbai, Maharashtra, India" },
  { main: "Kurla East", secondary: "Mumbai, Maharashtra, India" },
  { main: "Ghatkopar West", secondary: "Mumbai, Maharashtra, India" },
  { main: "Ghatkopar East", secondary: "Mumbai, Maharashtra, India" },
  { main: "Vikhroli West", secondary: "Mumbai, Maharashtra, India" },
  { main: "Vikhroli East", secondary: "Mumbai, Maharashtra, India" },
  { main: "Mulund West", secondary: "Mumbai, Maharashtra, India" },
  { main: "Mulund East", secondary: "Mumbai, Maharashtra, India" },
  { main: "Bhandup West", secondary: "Mumbai, Maharashtra, India" },
  { main: "Bhandup East", secondary: "Mumbai, Maharashtra, India" },
  { main: "Kanjurmarg West", secondary: "Mumbai, Maharashtra, India" },
  { main: "Kanjurmarg East", secondary: "Mumbai, Maharashtra, India" },
  { main: "Chembur", secondary: "Mumbai, Maharashtra, India" },
  { main: "Tilak Nagar", secondary: "Mumbai, Maharashtra, India" },
  { main: "Govandi", secondary: "Mumbai, Maharashtra, India" },
  { main: "Mankhurd", secondary: "Mumbai, Maharashtra, India" },
  { main: "Trombay", secondary: "Mumbai, Maharashtra, India" },
  { main: "Fort", secondary: "Mumbai, Maharashtra, India" },
  { main: "Colaba", secondary: "Mumbai, Maharashtra, India" },
  { main: "Nariman Point", secondary: "Mumbai, Maharashtra, India" },
  { main: "Churchgate", secondary: "Mumbai, Maharashtra, India" },
  { main: "Marine Drive", secondary: "Mumbai, Maharashtra, India" },
  { main: "Malabar Hill", secondary: "Mumbai, Maharashtra, India" },
  { main: "Breach Candy", secondary: "Mumbai, Maharashtra, India" },
  { main: "Kemps Corner", secondary: "Mumbai, Maharashtra, India" },
  { main: "Grant Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Opera House", secondary: "Mumbai, Maharashtra, India" },
  { main: "Charni Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Marine Lines", secondary: "Mumbai, Maharashtra, India" },
  { main: "Mumbai Central", secondary: "Mumbai, Maharashtra, India" },
  { main: "Mahalaxmi", secondary: "Mumbai, Maharashtra, India" },
  { main: "Elphinstone Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Chinchpokli", secondary: "Mumbai, Maharashtra, India" },
  { main: "Currey Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Parel", secondary: "Mumbai, Maharashtra, India" },
  { main: "Tardeo", secondary: "Mumbai, Maharashtra, India" },
  { main: "Haji Ali", secondary: "Mumbai, Maharashtra, India" },
  { main: "Pedder Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Cumballa Hill", secondary: "Mumbai, Maharashtra, India" },
  { main: "Walkeshwar", secondary: "Mumbai, Maharashtra, India" },
  { main: "Girgaon", secondary: "Mumbai, Maharashtra, India" },
  { main: "Kalbadevi", secondary: "Mumbai, Maharashtra, India" },
  { main: "Crawford Market", secondary: "Mumbai, Maharashtra, India" },
  { main: "Zaveri Bazaar", secondary: "Mumbai, Maharashtra, India" },
  { main: "Mohammed Ali Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Null Bazaar", secondary: "Mumbai, Maharashtra, India" },
  { main: "Mazgaon", secondary: "Mumbai, Maharashtra, India" },
  { main: "Sewri", secondary: "Mumbai, Maharashtra, India" },
  { main: "Cotton Green", secondary: "Mumbai, Maharashtra, India" },
  { main: "Reay Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Dockyard Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Sandhurst Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Byculla", secondary: "Mumbai, Maharashtra, India" },
  { main: "Agripada", secondary: "Mumbai, Maharashtra, India" },
  { main: "Nagpada", secondary: "Mumbai, Maharashtra, India" },
  { main: "Bhendi Bazaar", secondary: "Mumbai, Maharashtra, India" },
  { main: "Dongri", secondary: "Mumbai, Maharashtra, India" },
  { main: "Pydhonie", secondary: "Mumbai, Maharashtra, India" },
  { main: "Mandvi", secondary: "Mumbai, Maharashtra, India" },
  { main: "Ballard Estate", secondary: "Mumbai, Maharashtra, India" },
  { main: "Cuffe Parade", secondary: "Mumbai, Maharashtra, India" },
  { main: "World Trade Centre", secondary: "Mumbai, Maharashtra, India" },
  { main: "Backbay Reclamation", secondary: "Mumbai, Maharashtra, India" },
  { main: "Nepean Sea Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Altamount Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Carmichael Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Warden Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Bhulabhai Desai Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Napean Sea Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Hanging Garden", secondary: "Mumbai, Maharashtra, India" },
  { main: "Priyadarshini Park", secondary: "Mumbai, Maharashtra, India" },
  { main: "Shivaji Park", secondary: "Mumbai, Maharashtra, India" },
  { main: "Ruia Park", secondary: "Mumbai, Maharashtra, India" },
  { main: "Portuguese Church", secondary: "Mumbai, Maharashtra, India" },
  { main: "Five Gardens", secondary: "Mumbai, Maharashtra, India" },
  { main: "Hindu Colony", secondary: "Mumbai, Maharashtra, India" },
  { main: "Plaza Cinema", secondary: "Mumbai, Maharashtra, India" },
  { main: "Kabutarkhana", secondary: "Mumbai, Maharashtra, India" },
  { main: "Lady Jamshedji Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Cadell Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Senapati Bapat Marg", secondary: "Mumbai, Maharashtra, India" },
  { main: "Dr. Annie Besant Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "Tulsi Pipe Road", secondary: "Mumbai, Maharashtra, India" },
  { main: "N.M. Joshi Marg", secondary: "Mumbai, Maharashtra, India" },
  { main: "Lalbaug", secondary: "Mumbai, Maharashtra, India" },
  { main: "Parel Village", secondary: "Mumbai, Maharashtra, India" },
  { main: "Naigaon", secondary: "Mumbai, Maharashtra, India" },
  { main: "Antop Hill", secondary: "Mumbai, Maharashtra, India" },
  { main: "Anik", secondary: "Mumbai, Maharashtra, India" },
  { main: "Chunabhatti", secondary: "Mumbai, Maharashtra, India" },
  { main: "Suman Nagar", secondary: "Mumbai, Maharashtra, India" },
  { main: "Cheeta Camp", secondary: "Mumbai, Maharashtra, India" },
  { main: "Deonar", secondary: "Mumbai, Maharashtra, India" },
  { main: "Shivaji Nagar", secondary: "Mumbai, Maharashtra, India" },
  { main: "Rafiq Nagar", secondary: "Mumbai, Maharashtra, India" },

  // Delhi Areas (Expanded)
  { main: "Connaught Place", secondary: "Delhi, India" },
  { main: "Karol Bagh", secondary: "Delhi, India" },
  { main: "Lajpat Nagar", secondary: "Delhi, India" },
  { main: "Khan Market", secondary: "Delhi, India" },
  { main: "Saket", secondary: "Delhi, India" },
  { main: "Vasant Kunj", secondary: "Delhi, India" },
  { main: "Vasant Vihar", secondary: "Delhi, India" },
  { main: "Greater Kailash", secondary: "Delhi, India" },
  { main: "Defence Colony", secondary: "Delhi, India" },
  { main: "Lodi Road", secondary: "Delhi, India" },
  { main: "Hauz Khas", secondary: "Delhi, India" },
  { main: "Green Park", secondary: "Delhi, India" },
  { main: "Safdarjung", secondary: "Delhi, India" },
  { main: "Nehru Place", secondary: "Delhi, India" },
  { main: "Kalkaji", secondary: "Delhi, India" },
  { main: "Okhla", secondary: "Delhi, India" },
  { main: "Malviya Nagar", secondary: "Delhi, India" },
  { main: "R.K. Puram", secondary: "Delhi, India" },
  { main: "Munirka", secondary: "Delhi, India" },
  { main: "Janakpuri", secondary: "Delhi, India" },
  { main: "Rajouri Garden", secondary: "Delhi, India" },
  { main: "Tilak Nagar", secondary: "Delhi, India" },
  { main: "Subhash Nagar", secondary: "Delhi, India" },
  { main: "Tagore Garden", secondary: "Delhi, India" },
  { main: "Kirti Nagar", secondary: "Delhi, India" },
  { main: "Ramesh Nagar", secondary: "Delhi, India" },
  { main: "Moti Nagar", secondary: "Delhi, India" },
  { main: "Shahdara", secondary: "Delhi, India" },
  { main: "Preet Vihar", secondary: "Delhi, India" },
  { main: "Laxmi Nagar", secondary: "Delhi, India" },
  { main: "Mayur Vihar", secondary: "Delhi, India" },
  { main: "Patparganj", secondary: "Delhi, India" },
  { main: "Anand Vihar", secondary: "Delhi, India" },
  { main: "Karkardooma", secondary: "Delhi, India" },
  { main: "Dilshad Garden", secondary: "Delhi, India" },
  { main: "Jhilmil", secondary: "Delhi, India" },
  { main: "Mansarovar Park", secondary: "Delhi, India" },
  { main: "Vivek Vihar", secondary: "Delhi, India" },
  { main: "Rohini", secondary: "Delhi, India" },
  { main: "Pitampura", secondary: "Delhi, India" },
  { main: "Kohat Enclave", secondary: "Delhi, India" },
  { main: "Shalimar Bagh", secondary: "Delhi, India" },
  { main: "Ashok Vihar", secondary: "Delhi, India" },
  { main: "Wazirabad", secondary: "Delhi, India" },
  { main: "Model Town", secondary: "Delhi, India" },
  { main: "Civil Lines", secondary: "Delhi, India" },
  { main: "Kamla Nagar", secondary: "Delhi, India" },
  { main: "Mukherjee Nagar", secondary: "Delhi, India" },
  { main: "Timarpur", secondary: "Delhi, India" },
  { main: "Burari", secondary: "Delhi, India" },
  { main: "Dwarka", secondary: "Delhi, India" },
  { main: "Uttam Nagar", secondary: "Delhi, India" },
  { main: "Najafgarh", secondary: "Delhi, India" },
  { main: "Palam", secondary: "Delhi, India" },
  { main: "Mahipalpur", secondary: "Delhi, India" },
  { main: "Kapashera", secondary: "Delhi, India" },
  { main: "Chhattarpur", secondary: "Delhi, India" },
  { main: "Mehrauli", secondary: "Delhi, India" },
  { main: "Qutub Minar", secondary: "Delhi, India" },
  { main: "Lado Sarai", secondary: "Delhi, India" },
  { main: "Saidulajab", secondary: "Delhi, India" },
  { main: "Pushp Vihar", secondary: "Delhi, India" },
  { main: "Sheikh Sarai", secondary: "Delhi, India" },
  { main: "Panchsheel Park", secondary: "Delhi, India" },
  { main: "Chirag Delhi", secondary: "Delhi, India" },
  { main: "Greater Kailash I", secondary: "Delhi, India" },
  { main: "Greater Kailash II", secondary: "Delhi, India" },
  { main: "Kailash Colony", secondary: "Delhi, India" },
  { main: "East of Kailash", secondary: "Delhi, India" },
  { main: "Alaknanda", secondary: "Delhi, India" },
  { main: "Kalkaji Extension", secondary: "Delhi, India" },
  { main: "Govindpuri", secondary: "Delhi, India" },
  { main: "Tughlakabad", secondary: "Delhi, India" },
  { main: "Badarpur", secondary: "Delhi, India" },
  { main: "Faridabad Border", secondary: "Delhi, India" },
  { main: "Jasola", secondary: "Delhi, India" },
  { main: "Apollo Hospital", secondary: "Delhi, India" },
  { main: "Sarita Vihar", secondary: "Delhi, India" },
  { main: "Mathura Road", secondary: "Delhi, India" },
  { main: "Jangpura", secondary: "Delhi, India" },
  { main: "Nizamuddin", secondary: "Delhi, India" },
  { main: "Humayun Tomb", secondary: "Delhi, India" },
  { main: "Lodhi Gardens", secondary: "Delhi, India" },
  { main: "India Habitat Centre", secondary: "Delhi, India" },
  { main: "Max Hospital", secondary: "Delhi, India" },
  { main: "AIIMS", secondary: "Delhi, India" },
  { main: "IIT Delhi", secondary: "Delhi, India" },
  { main: "JNU", secondary: "Delhi, India" },
  { main: "Jamia Millia Islamia", secondary: "Delhi, India" },
  { main: "Delhi University", secondary: "Delhi, India" },
  { main: "Hindu College", secondary: "Delhi, India" },
  { main: "St. Stephen's College", secondary: "Delhi, India" },
  { main: "Lady Shri Ram College", secondary: "Delhi, India" },
  { main: "Miranda House", secondary: "Delhi, India" },
  { main: "Hansraj College", secondary: "Delhi, India" },
  { main: "Ramjas College", secondary: "Delhi, India" },
  { main: "Kirori Mal College", secondary: "Delhi, India" },
  { main: "Daulat Ram College", secondary: "Delhi, India" },
  { main: "Gargi College", secondary: "Delhi, India" },
  { main: "Jesus and Mary College", secondary: "Delhi, India" },
  { main: "Indraprastha College", secondary: "Delhi, India" },

  // Bangalore Areas (Expanded)
  { main: "Koramangala", secondary: "Bangalore, Karnataka, India" },
  { main: "Indiranagar", secondary: "Bangalore, Karnataka, India" },
  { main: "Jayanagar", secondary: "Bangalore, Karnataka, India" },
  { main: "BTM Layout", secondary: "Bangalore, Karnataka, India" },
  { main: "HSR Layout", secondary: "Bangalore, Karnataka, India" },
  { main: "Marathahalli", secondary: "Bangalore, Karnataka, India" },
  { main: "Whitefield", secondary: "Bangalore, Karnataka, India" },
  { main: "Electronic City", secondary: "Bangalore, Karnataka, India" },
  { main: "Banashankari", secondary: "Bangalore, Karnataka, India" },
  { main: "Basavanagudi", secondary: "Bangalore, Karnataka, India" },
  { main: "Malleshwaram", secondary: "Bangalore, Karnataka, India" },
  { main: "Rajajinagar", secondary: "Bangalore, Karnataka, India" },
  { main: "Vijayanagar", secondary: "Bangalore, Karnataka, India" },
  { main: "Yeshwanthpur", secondary: "Bangalore, Karnataka, India" },
  { main: "Hebbal", secondary: "Bangalore, Karnataka, India" },
  { main: "RT Nagar", secondary: "Bangalore, Karnataka, India" },
  { main: "Yelahanka", secondary: "Bangalore, Karnataka, India" },
  { main: "Sarjapur Road", secondary: "Bangalore, Karnataka, India" },
  { main: "Outer Ring Road", secondary: "Bangalore, Karnataka, India" },
  { main: "Bellandur", secondary: "Bangalore, Karnataka, India" },
  { main: "Sarjapur", secondary: "Bangalore, Karnataka, India" },
  { main: "Bommanahalli", secondary: "Bangalore, Karnataka, India" },
  { main: "JP Nagar", secondary: "Bangalore, Karnataka, India" },
  { main: "Bannerghatta Road", secondary: "Bangalore, Karnataka, India" },
  { main: "Kanakapura Road", secondary: "Bangalore, Karnataka, India" },
  { main: "Mysore Road", secondary: "Bangalore, Karnataka, India" },
  { main: "Tumkur Road", secondary: "Bangalore, Karnataka, India" },
  { main: "Magadi Road", secondary: "Bangalore, Karnataka, India" },
  { main: "Chord Road", secondary: "Bangalore, Karnataka, India" },
  { main: "Richmond Road", secondary: "Bangalore, Karnataka, India" },
  { main: "Brigade Road", secondary: "Bangalore, Karnataka, India" },
  { main: "Commercial Street", secondary: "Bangalore, Karnataka, India" },
  { main: "MG Road", secondary: "Bangalore, Karnataka, India" },
  { main: "Cunningham Road", secondary: "Bangalore, Karnataka, India" },
  { main: "Residency Road", secondary: "Bangalore, Karnataka, India" },
  { main: "Lavelle Road", secondary: "Bangalore, Karnataka, India" },
  { main: "UB City Mall", secondary: "Bangalore, Karnataka, India" },
  { main: "Forum Mall", secondary: "Bangalore, Karnataka, India" },
  { main: "Orion Mall", secondary: "Bangalore, Karnataka, India" },
  { main: "Koramangala 1st Block", secondary: "Bangalore, Karnataka, India" },
  { main: "Koramangala 2nd Block", secondary: "Bangalore, Karnataka, India" },
  { main: "Koramangala 3rd Block", secondary: "Bangalore, Karnataka, India" },
  { main: "Koramangala 4th Block", secondary: "Bangalore, Karnataka, India" },
  { main: "Koramangala 5th Block", secondary: "Bangalore, Karnataka, India" },
  { main: "Koramangala 6th Block", secondary: "Bangalore, Karnataka, India" },
  { main: "Koramangala 7th Block", secondary: "Bangalore, Karnataka, India" },
  { main: "Koramangala 8th Block", secondary: "Bangalore, Karnataka, India" },
  { main: "Indiranagar 100 Feet Road", secondary: "Bangalore, Karnataka, India" },
  { main: "Indiranagar HAL 2nd Stage", secondary: "Bangalore, Karnataka, India" },
  { main: "Indiranagar HAL 3rd Stage", secondary: "Bangalore, Karnataka, India" },
  { main: "Domlur", secondary: "Bangalore, Karnataka, India" },
  { main: "Old Airport Road", secondary: "Bangalore, Karnataka, India" },
  { main: "New Airport Road", secondary: "Bangalore, Karnataka, India" },
  { main: "Ulsoor", secondary: "Bangalore, Karnataka, India" },
  { main: "Frazer Town", secondary: "Bangalore, Karnataka, India" },
  { main: "Cox Town", secondary: "Bangalore, Karnataka, India" },
  { main: "Pulakeshi Nagar", secondary: "Bangalore, Karnataka, India" },
  { main: "Shivaji Nagar", secondary: "Bangalore, Karnataka, India" },
  { main: "Vasanth Nagar", secondary: "Bangalore, Karnataka, India" },
  { main: "Sadashiva Nagar", secondary: "Bangalore, Karnataka, India" },
  { main: "Palace Guttahalli", secondary: "Bangalore, Karnataka, India" },
  { main: "Seshadripuram", secondary: "Bangalore, Karnataka, India" },
  { main: "Gandhinagar", secondary: "Bangalore, Karnataka, India" },
  { main: "Majestic", secondary: "Bangalore, Karnataka, India" },
  { main: "City Railway Station", secondary: "Bangalore, Karnataka, India" },
  { main: "Chickpet", secondary: "Bangalore, Karnataka, India" },
  { main: "Avenue Road", secondary: "Bangalore, Karnataka, India" },
  { main: "Shankarpuram", secondary: "Bangalore, Karnataka, India" },
  { main: "Chamarajpet", secondary: "Bangalore, Karnataka, India" },
  { main: "Balepet", secondary: "Bangalore, Karnataka, India" },
  { main: "Cottonpet", secondary: "Bangalore, Karnataka, India" },
  { main: "Nagarthpet", secondary: "Bangalore, Karnataka, India" },
  { main: "Sultanpet", secondary: "Bangalore, Karnataka, India" },
  { main: "Blackpally", secondary: "Bangalore, Karnataka, India" },
  { main: "Richmond Town", secondary: "Bangalore, Karnataka, India" },
  { main: "Langford Town", secondary: "Bangalore, Karnataka, India" },
  { main: "Ashok Nagar", secondary: "Bangalore, Karnataka, India" },
  { main: "Jayanagar 1st Block", secondary: "Bangalore, Karnataka, India" },
  { main: "Jayanagar 2nd Block", secondary: "Bangalore, Karnataka, India" },
  { main: "Jayanagar 3rd Block", secondary: "Bangalore, Karnataka, India" },
  { main: "Jayanagar 4th Block", secondary: "Bangalore, Karnataka, India" },
  { main: "Jayanagar 5th Block", secondary: "Bangalore, Karnataka, India" },
  { main: "Jayanagar 6th Block", secondary: "Bangalore, Karnataka, India" },
  { main: "Jayanagar 7th Block", secondary: "Bangalore, Karnataka, India" },
  { main: "Jayanagar 8th Block", secondary: "Bangalore, Karnataka, India" },
  { main: "Jayanagar 9th Block", secondary: "Bangalore, Karnataka, India" },
  { main: "BTM Layout 1st Stage", secondary: "Bangalore, Karnataka, India" },
  { main: "BTM Layout 2nd Stage", secondary: "Bangalore, Karnataka, India" },
  { main: "Madiwala", secondary: "Bangalore, Karnataka, India" },
  { main: "Tavarekere", secondary: "Bangalore, Karnataka, India" },
  { main: "5th Block Jayanagar", secondary: "Bangalore, Karnataka, India" },
  { main: "Lalbagh", secondary: "Bangalore, Karnataka, India" },
  { main: "Cubbon Park", secondary: "Bangalore, Karnataka, India" },
  { main: "Vidhana Soudha", secondary: "Bangalore, Karnataka, India" },
  { main: "High Court", secondary: "Bangalore, Karnataka, India" },
  { main: "Bangalore Palace", secondary: "Bangalore, Karnataka, India" },
  { main: "Tipu Sultan Palace", secondary: "Bangalore, Karnataka, India" },
  { main: "Bull Temple", secondary: "Bangalore, Karnataka, India" },
  { main: "ISKCON Temple", secondary: "Bangalore, Karnataka, India" },
  { main: "Bannerghatta National Park", secondary: "Bangalore, Karnataka, India" },
  { main: "Nandi Hills", secondary: "Bangalore, Karnataka, India" },
  { main: "Wonderla", secondary: "Bangalore, Karnataka, India" },
  { main: "Innovative Film City", secondary: "Bangalore, Karnataka, India" },

  // Popular Landmarks and Airports (Expanded)
  { main: "Chhatrapati Shivaji International Airport", secondary: "Mumbai, Maharashtra, India" },
  { main: "Indira Gandhi International Airport", secondary: "Delhi, India" },
  { main: "Kempegowda International Airport", secondary: "Bangalore, Karnataka, India" },
  { main: "Chennai International Airport", secondary: "Chennai, Tamil Nadu, India" },
  { main: "Rajiv Gandhi International Airport", secondary: "Hyderabad, Telangana, India" },
  { main: "Netaji Subhas Chandra Bose International Airport", secondary: "Kolkata, West Bengal, India" },
  { main: "Pune Airport", secondary: "Pune, Maharashtra, India" },
  { main: "Sardar Vallabhbhai Patel International Airport", secondary: "Ahmedabad, Gujarat, India" },
  { main: "Jaipur International Airport", secondary: "Jaipur, Rajasthan, India" },
  { main: "Cochin International Airport", secondary: "Kochi, Kerala, India" },
  { main: "Goa Airport", secondary: "Goa, India" },
  { main: "Trivandrum International Airport", secondary: "Thiruvananthapuram, Kerala, India" },
  { main: "Calicut International Airport", secondary: "Kozhikode, Kerala, India" },
  { main: "Mangalore Airport", secondary: "Mangalore, Karnataka, India" },
  { main: "Coimbatore Airport", secondary: "Coimbatore, Tamil Nadu, India" },
  { main: "Madurai Airport", secondary: "Madurai, Tamil Nadu, India" },
  { main: "Tiruchirapalli Airport", secondary: "Tiruchirappalli, Tamil Nadu, India" },
  { main: "Visakhapatnam Airport", secondary: "Visakhapatnam, Andhra Pradesh, India" },
  { main: "Vijayawada Airport", secondary: "Vijayawada, Andhra Pradesh, India" },
  { main: "Tirupati Airport", secondary: "Tirupati, Andhra Pradesh, India" },

  // Railway Stations (Expanded)
  { main: "Chhatrapati Shivaji Terminus", secondary: "Mumbai, Maharashtra, India" },
  { main: "New Delhi Railway Station", secondary: "Delhi, India" },
  { main: "Howrah Junction", secondary: "Kolkata, West Bengal, India" },
  { main: "Chennai Central", secondary: "Chennai, Tamil Nadu, India" },
  { main: "Bangalore City Railway Station", secondary: "Bangalore, Karnataka, India" },
  { main: "Secunderabad Junction", secondary: "Hyderabad, Telangana, India" },
  { main: "Pune Junction", secondary: "Pune, Maharashtra, India" },
  { main: "Ahmedabad Junction", secondary: "Ahmedabad, Gujarat, India" },
  { main: "Jaipur Junction", secondary: "Jaipur, Rajasthan, India" },
  { main: "Lucknow Junction", secondary: "Lucknow, Uttar Pradesh, India" },
  { main: "Kanpur Central", secondary: "Kanpur, Uttar Pradesh, India" },
  { main: "Nagpur Junction", secondary: "Nagpur, Maharashtra, India" },
  { main: "Bhopal Junction", secondary: "Bhopal, Madhya Pradesh, India" },
  { main: "Indore Junction", secondary: "Indore, Madhya Pradesh, India" },
  { main: "Surat Railway Station", secondary: "Surat, Gujarat, India" },
  { main: "Vadodara Junction", secondary: "Vadodara, Gujarat, India" },
  { main: "Rajkot Junction", secondary: "Rajkot, Gujarat, India" },
  { main: "Jodhpur Junction", secondary: "Jodhpur, Rajasthan, India" },
  { main: "Bikaner Junction", secondary: "Bikaner, Rajasthan, India" },
  { main: "Ajmer Junction", secondary: "Ajmer, Rajasthan, India" },
  { main: "Kota Junction", secondary: "Kota, Rajasthan, India" },
  { main: "Udaipur City", secondary: "Udaipur, Rajasthan, India" },
  { main: "Agra Cantt", secondary: "Agra, Uttar Pradesh, India" },
  { main: "Mathura Junction", secondary: "Mathura, Uttar Pradesh, India" },
  { main: "Varanasi Junction", secondary: "Varanasi, Uttar Pradesh, India" },
  { main: "Allahabad Junction", secondary: "Allahabad, Uttar Pradesh, India" },
  { main: "Gorakhpur Junction", secondary: "Gorakhpur, Uttar Pradesh, India" },
  { main: "Bareilly Junction", secondary: "Bareilly, Uttar Pradesh, India" },
  { main: "Moradabad Junction", secondary: "Moradabad, Uttar Pradesh, India" },
  { main: "Dehradun Railway Station", secondary: "Dehradun, Uttarakhand, India" },
  { main: "Haridwar Junction", secondary: "Haridwar, Uttarakhand, India" },
  { main: "Rishikesh Railway Station", secondary: "Rishikesh, Uttarakhand, India" },
  { main: "Chandigarh Railway Station", secondary: "Chandigarh, India" },
  { main: "Ludhiana Junction", secondary: "Ludhiana, Punjab, India" },
  { main: "Amritsar Junction", secondary: "Amritsar, Punjab, India" },
  { main: "Jalandhar City", secondary: "Jalandhar, Punjab, India" },
  { main: "Pathankot Junction", secondary: "Pathankot, Punjab, India" },
  { main: "Jammu Tawi", secondary: "Jammu, Jammu and Kashmir, India" },
  { main: "Srinagar Railway Station", secondary: "Srinagar, Jammu and Kashmir, India" },
  { main: "Shimla Railway Station", secondary: "Shimla, Himachal Pradesh, India" },
  { main: "Kalka Railway Station", secondary: "Kalka, Haryana, India" },
  { main: "Ambala Cantt", secondary: "Ambala, Haryana, India" },
  { main: "Kurukshetra Junction", secondary: "Kurukshetra, Haryana, India" },
  { main: "Panipat Junction", secondary: "Panipat, Haryana, India" },
  { main: "Sonipat Junction", secondary: "Sonipat, Haryana, India" },
  { main: "Rohtak Junction", secondary: "Rohtak, Haryana, India" },
  { main: "Hisar Junction", secondary: "Hisar, Haryana, India" },
  { main: "Sirsa Junction", secondary: "Sirsa, Haryana, India" },
  { main: "Faridabad Railway Station", secondary: "Faridabad, Haryana, India" },
  { main: "Gurgaon Railway Station", secondary: "Gurgaon, Haryana, India" },
  { main: "Palwal Junction", secondary: "Palwal, Haryana, India" },
  { main: "Rewari Junction", secondary: "Rewari, Haryana, India" },
  { main: "Bhiwani Junction", secondary: "Bhiwani, Haryana, India" },
  { main: "Mahendragarh Railway Station", secondary: "Mahendragarh, Haryana, India" },

  // Tourist Places (Expanded)
  { main: "Gateway of India", secondary: "Mumbai, Maharashtra, India" },
  { main: "India Gate", secondary: "Delhi, India" },
  { main: "Red Fort", secondary: "Delhi, India" },
  { main: "Qutub Minar", secondary: "Delhi, India" },
  { main: "Lotus Temple", secondary: "Delhi, India" },
  { main: "Akshardham Temple", secondary: "Delhi, India" },
  { main: "Taj Mahal", secondary: "Agra, Uttar Pradesh, India" },
  { main: "Hawa Mahal", secondary: "Jaipur, Rajasthan, India" },
  { main: "City Palace", secondary: "Jaipur, Rajasthan, India" },
  { main: "Amber Fort", secondary: "Jaipur, Rajasthan, India" },
  { main: "Golden Temple", secondary: "Amritsar, Punjab, India" },
  { main: "Victoria Memorial", secondary: "Kolkata, West Bengal, India" },
  { main: "Mysore Palace", secondary: "Mysore, Karnataka, India" },
  { main: "Charminar", secondary: "Hyderabad, Telangana, India" },
  { main: "Marina Beach", secondary: "Chennai, Tamil Nadu, India" },
  { main: "Backwaters", secondary: "Alleppey, Kerala, India" },
  { main: "Munnar", secondary: "Kerala, India" },
  { main: "Goa Beaches", secondary: "Goa, India" },
  { main: "Hampi", secondary: "Karnataka, India" },
  { main: "Khajuraho", secondary: "Madhya Pradesh, India" },
  { main: "Vaishno Devi", secondary: "Jammu and Kashmir, India" },
  { main: "Kedarnath", secondary: "Uttarakhand, India" },
  { main: "Badrinath", secondary: "Uttarakhand, India" },
  { main: "Haridwar", secondary: "Uttarakhand, India" },
  { main: "Rishikesh", secondary: "Uttarakhand, India" },
  { main: "Mussoorie", secondary: "Uttarakhand, India" },
  { main: "Nainital", secondary: "Uttarakhand, India" },
  { main: "Jim Corbett National Park", secondary: "Uttarakhand, India" },
  { main: "Valley of Flowers", secondary: "Uttarakhand, India" },
  { main: "Char Dham", secondary: "Uttarakhand, India" },
  { main: "Gangotri", secondary: "Uttarakhand, India" },
  { main: "Yamunotri", secondary: "Uttarakhand, India" },
  { main: "Hemkund Sahib", secondary: "Uttarakhand, India" },
  { main: "Auli", secondary: "Uttarakhand, India" },
  { main: "Chopta", secondary: "Uttarakhand, India" },
  { main: "Lansdowne", secondary: "Uttarakhand, India" },
  { main: "Almora", secondary: "Uttarakhand, India" },
  { main: "Ranikhet", secondary: "Uttarakhand, India" },
  { main: "Kausani", secondary: "Uttarakhand, India" },
  { main: "Pithoragarh", secondary: "Uttarakhand, India" },
  { main: "Bageshwar", secondary: "Uttarakhand, India" },
  { main: "Chamoli", secondary: "Uttarakhand, India" },
  { main: "Rudraprayag", secondary: "Uttarakhand, India" },
  { main: "Tehri", secondary: "Uttarakhand, India" },
  { main: "Pauri", secondary: "Uttarakhand, India" },
  { main: "Shimla", secondary: "Himachal Pradesh, India" },
  { main: "Manali", secondary: "Himachal Pradesh, India" },
  { main: "Dharamshala", secondary: "Himachal Pradesh, India" },
  { main: "McLeod Ganj", secondary: "Himachal Pradesh, India" },
  { main: "Dalhousie", secondary: "Himachal Pradesh, India" },
  { main: "Kasauli", secondary: "Himachal Pradesh, India" },
  { main: "Kullu", secondary: "Himachal Pradesh, India" },
  { main: "Spiti Valley", secondary: "Himachal Pradesh, India" },
  { main: "Kinnaur", secondary: "Himachal Pradesh, India" },
  { main: "Lahaul", secondary: "Himachal Pradesh, India" },
  { main: "Rohtang Pass", secondary: "Himachal Pradesh, India" },
  { main: "Solang Valley", secondary: "Himachal Pradesh, India" },
  { main: "Khajjiar", secondary: "Himachal Pradesh, India" },
  { main: "Chamba", secondary: "Himachal Pradesh, India" },
  { main: "Kangra", secondary: "Himachal Pradesh, India" },
  { main: "Palampur", secondary: "Himachal Pradesh, India" },
  { main: "Bir Billing", secondary: "Himachal Pradesh, India" },
  { main: "Tirthan Valley", secondary: "Himachal Pradesh, India" },
  { main: "Malana", secondary: "Himachal Pradesh, India" },
  { main: "Kasol", secondary: "Himachal Pradesh, India" },
  { main: "Tosh", secondary: "Himachal Pradesh, India" },
  { main: "Kheerganga", secondary: "Himachal Pradesh, India" },
  { main: "Parvati Valley", secondary: "Himachal Pradesh, India" },
  { main: "Pin Valley", secondary: "Himachal Pradesh, India" },
  { main: "Sangla", secondary: "Himachal Pradesh, India" },
  { main: "Chitkul", secondary: "Himachal Pradesh, India" },
  { main: "Kalpa", secondary: "Himachal Pradesh, India" },
  { main: "Reckong Peo", secondary: "Himachal Pradesh, India" },
  { main: "Nako", secondary: "Himachal Pradesh, India" },
  { main: "Tabo", secondary: "Himachal Pradesh, India" },
  { main: "Kaza", secondary: "Himachal Pradesh, India" },
  { main: "Key Monastery", secondary: "Himachal Pradesh, India" },
  { main: "Chandratal Lake", secondary: "Himachal Pradesh, India" },
  { main: "Suraj Tal", secondary: "Himachal Pradesh, India" },
  { main: "Baralacha Pass", secondary: "Himachal Pradesh, India" },
  { main: "Kunzum Pass", secondary: "Himachal Pradesh, India" },
  { main: "Leh", secondary: "Ladakh, India" },
  { main: "Ladakh", secondary: "Jammu and Kashmir, India" },
  { main: "Kargil", secondary: "Ladakh, India" },
  { main: "Nubra Valley", secondary: "Ladakh, India" },
  { main: "Pangong Lake", secondary: "Ladakh, India" },
  { main: "Tso Moriri", secondary: "Ladakh, India" },
  { main: "Magnetic Hill", secondary: "Ladakh, India" },
  { main: "Khardung La", secondary: "Ladakh, India" },
  { main: "Chang La", secondary: "Ladakh, India" },
  { main: "Zanskar Valley", secondary: "Ladakh, India" },
  { main: "Hemis Monastery", secondary: "Ladakh, India" },
  { main: "Thiksey Monastery", secondary: "Ladakh, India" },
  { main: "Diskit Monastery", secondary: "Ladakh, India" },
  { main: "Shanti Stupa", secondary: "Ladakh, India" },
  { main: "Leh Palace", secondary: "Ladakh, India" },
  { main: "Hall of Fame", secondary: "Ladakh, India" },
  { main: "Gulmarg", secondary: "Jammu and Kashmir, India" },
  { main: "Pahalgam", secondary: "Jammu and Kashmir, India" },
  { main: "Sonamarg", secondary: "Jammu and Kashmir, India" },
  { main: "Dal Lake", secondary: "Srinagar, Jammu and Kashmir, India" },
  { main: "Nigeen Lake", secondary: "Srinagar, Jammu and Kashmir, India" },
  { main: "Shalimar Bagh", secondary: "Srinagar, Jammu and Kashmir, India" },
  { main: "Nishat Bagh", secondary: "Srinagar, Jammu and Kashmir, India" },
  { main: "Chashme Shahi", secondary: "Srinagar, Jammu and Kashmir, India" },
  { main: "Hazratbal Shrine", secondary: "Srinagar, Jammu and Kashmir, India" },
  { main: "Jama Masjid", secondary: "Srinagar, Jammu and Kashmir, India" },
  { main: "Shankaracharya Temple", secondary: "Srinagar, Jammu and Kashmir, India" },
  { main: "Pari Mahal", secondary: "Srinagar, Jammu and Kashmir, India" },
  { main: "Betaab Valley", secondary: "Pahalgam, Jammu and Kashmir, India" },
  { main: "Aru Valley", secondary: "Pahalgam, Jammu and Kashmir, India" },
  { main: "Chandanwari", secondary: "Pahalgam, Jammu and Kashmir, India" },
  { main: "Amarnath Cave", secondary: "Jammu and Kashmir, India" },
  { main: "Patnitop", secondary: "Jammu and Kashmir, India" },
  { main: "Bhaderwah", secondary: "Jammu and Kashmir, India" },
  { main: "Kishtwar", secondary: "Jammu and Kashmir, India" },
  { main: "Doda", secondary: "Jammu and Kashmir, India" },
  { main: "Ramban", secondary: "Jammu and Kashmir, India" },
  { main: "Banihal", secondary: "Jammu and Kashmir, India" },
  { main: "Qazigund", secondary: "Jammu and Kashmir, India" },
  { main: "Anantnag", secondary: "Jammu and Kashmir, India" },
  { main: "Kokernag", secondary: "Jammu and Kashmir, India" },
  { main: "Verinag", secondary: "Jammu and Kashmir, India" },
  { main: "Achabal", secondary: "Jammu and Kashmir, India" },
  { main: "Martand Sun Temple", secondary: "Jammu and Kashmir, India" },
  { main: "Awantipora", secondary: "Jammu and Kashmir, India" },
  { main: "Pulwama", secondary: "Jammu and Kashmir, India" },
  { main: "Shopian", secondary: "Jammu and Kashmir, India" },
  { main: "Kulgam", secondary: "Jammu and Kashmir, India" },
  { main: "Budgam", secondary: "Jammu and Kashmir, India" },
  { main: "Chadoura", secondary: "Jammu and Kashmir, India" },
  { main: "Charar-e-Sharief", secondary: "Jammu and Kashmir, India" },
  { main: "Ganderbal", secondary: "Jammu and Kashmir, India" },
  { main: "Kangan", secondary: "Jammu and Kashmir, India" },
  { main: "Gund", secondary: "Jammu and Kashmir, India" },
  { main: "Baltal", secondary: "Jammu and Kashmir, India" },
  { main: "Thajiwas Glacier", secondary: "Sonamarg, Jammu and Kashmir, India" },
  { main: "Zoji La", secondary: "Jammu and Kashmir, India" },
  { main: "Drass", secondary: "Ladakh, India" },
  { main: "Mulbekh", secondary: "Ladakh, India" },
  { main: "Lamayuru", secondary: "Ladakh, India" },
  { main: "Alchi", secondary: "Ladakh, India" },
  { main: "Likir", secondary: "Ladakh, India" },
  { main: "Basgo", secondary: "Ladakh, India" },
  { main: "Nimmu", secondary: "Ladakh, India" },
  { main: "Phyang", secondary: "Ladakh, India" },
  { main: "Spituk", secondary: "Ladakh, India" },
  { main: "Stok", secondary: "Ladakh, India" },
  { main: "Matho", secondary: "Ladakh, India" },
  { main: "Stakna", secondary: "Ladakh, India" },
  { main: "Chemrey", secondary: "Ladakh, India" },
  { main: "Takthok", secondary: "Ladakh, India" },
  { main: "Sakti", secondary: "Ladakh, India" },
  { main: "Tangtse", secondary: "Ladakh, India" },
  { main: "Durbuk", secondary: "Ladakh, India" },
  { main: "Shyok", secondary: "Ladakh, India" },
  { main: "Khalsar", secondary: "Ladakh, India" },
  { main: "Sumur", secondary: "Ladakh, India" },
  { main: "Panamik", secondary: "Ladakh, India" },
  { main: "Turtuk", secondary: "Ladakh, India" },
  { main: "Tyakshi", secondary: "Ladakh, India" },
  { main: "Bogdang", secondary: "Ladakh, India" },
  { main: "Warshi", secondary: "Ladakh, India" },
  { main: "Chuchot", secondary: "Ladakh, India" },
  { main: "Saboo", secondary: "Ladakh, India" },
  { main: "Phey", secondary: "Ladakh, India" },
  { main: "Nimmu", secondary: "Ladakh, India" },
  { main: "Saspol", secondary: "Ladakh, India" },
  { main: "Temisgang", secondary: "Ladakh, India" },
  { main: "Nurla", secondary: "Ladakh, India" },
  { main: "Sham Valley", secondary: "Ladakh, India" },
  { main: "Markha Valley", secondary: "Ladakh, India" },
  { main: "Rumbak", secondary: "Ladakh, India" },
  { main: "Zinchen", secondary: "Ladakh, India" },
  { main: "Yurutse", secondary: "Ladakh, India" },
  { main: "Shingo", secondary: "Ladakh, India" },
  { main: "Nimaling", secondary: "Ladakh, India" },
  { main: "Chokdo", secondary: "Ladakh, India" },
  { main: "Skiu", secondary: "Ladakh, India" },
  { main: "Markha", secondary: "Ladakh, India" },
  { main: "Hankar", secondary: "Ladakh, India" },
  { main: "Thachungtse", secondary: "Ladakh, India" },
  { main: "Kongmaru La", secondary: "Ladakh, India" },
  { main: "Hemis Shukpachan", secondary: "Ladakh, India" },
  { main: "Ang", secondary: "Ladakh, India" },
  { main: "Temisgam", secondary: "Ladakh, India" },
  { main: "Wanla", secondary: "Ladakh, India" },
  { main: "Phanjila", secondary: "Ladakh, India" },
  { main: "Hinju", secondary: "Ladakh, India" },
  { main: "Sumda Chenmo", secondary: "Ladakh, India" },
  { main: "Sumda Chun", secondary: "Ladakh, India" },
  { main: "Chilling", secondary: "Ladakh, India" },
  { main: "Zangla", secondary: "Ladakh, India" },
  { main: "Pidmo", secondary: "Ladakh, India" },
  { main: "Hanumil", secondary: "Ladakh, India" },
  { main: "Lingshed", secondary: "Ladakh, India" },
  { main: "Nyerak", secondary: "Ladakh, India" },
  { main: "Snertse", secondary: "Ladakh, India" },
  { main: "Hanumil", secondary: "Ladakh, India" },
  { main: "Photoksar", secondary: "Ladakh, India" },
  { main: "Sirsir La", secondary: "Ladakh, India" },
  { main: "Singge La", secondary: "Ladakh, India" },
  { main: "Kanji", secondary: "Ladakh, India" },
  { main: "Rangdum", secondary: "Ladakh, India" },
  { main: "Padum", secondary: "Ladakh, India" },
  { main: "Karsha", secondary: "Ladakh, India" },
  { main: "Stongde", secondary: "Ladakh, India" },
  { main: "Sani", secondary: "Ladakh, India" },
  { main: "Anmu", secondary: "Ladakh, India" },
  { main: "Cha", secondary: "Ladakh, India" },
  { main: "Purne", secondary: "Ladakh, India" },
  { main: "Phuktal", secondary: "Ladakh, India" },
  { main: "Bardan", secondary: "Ladakh, India" },
  { main: "Mune", secondary: "Ladakh, India" },
  { main: "Ichar", secondary: "Ladakh, India" },
  { main: "Zangla", secondary: "Ladakh, India" },
  { main: "Hanamur", secondary: "Ladakh, India" },
  { main: "Pishu", secondary: "Ladakh, India" },
  { main: "Reru", secondary: "Ladakh, India" },
  { main: "Testa", secondary: "Ladakh, India" },
  { main: "Hankar Phu", secondary: "Ladakh, India" },
  { main: "Shade", secondary: "Ladakh, India" },
  { main: "Kuru", secondary: "Ladakh, India" },
  { main: "Thonde", secondary: "Ladakh, India" },
  { main: "Remala", secondary: "Ladakh, India" },
  { main: "Lakong", secondary: "Ladakh, India" },
  { main: "Skyumpata", secondary: "Ladakh, India" },
  { main: "Skyangpoche", secondary: "Ladakh, India" },
  { main: "Leh Manali Highway", secondary: "Ladakh, India" },
  { main: "Srinagar Leh Highway", secondary: "Ladakh, India" },
  { main: "Manali Leh Highway", secondary: "Himachal Pradesh to Ladakh, India" },
  { main: "Keylong", secondary: "Himachal Pradesh, India" },
  { main: "Jispa", secondary: "Himachal Pradesh, India" },
  { main: "Darcha", secondary: "Himachal Pradesh, India" },
  { main: "Zingzingbar", secondary: "Himachal Pradesh, India" },
  { main: "Sarchu", secondary: "Himachal Pradesh, India" },
  { main: "Nakee La", secondary: "Himachal Pradesh, India" },
  { main: "Lachulung La", secondary: "Himachal Pradesh, India" },
  { main: "Pang", secondary: "Ladakh, India" },
  { main: "More Plains", secondary: "Ladakh, India" },
  { main: "Debring", secondary: "Ladakh, India" },
  { main: "Rumtse", secondary: "Ladakh, India" },
  { main: "Upshi", secondary: "Ladakh, India" },
  { main: "Karu", secondary: "Ladakh, India" },
  { main: "Thiksey", secondary: "Ladakh, India" },
  { main: "Shey", secondary: "Ladakh, India" },
  { main: "Choglamsar", secondary: "Ladakh, India" },
  { main: "Spituk", secondary: "Ladakh, India" },
  { main: "Phyang", secondary: "Ladakh, India" },
  { main: "Nimmu", secondary: "Ladakh, India" },
  { main: "Basgo", secondary: "Ladakh, India" },
  { main: "Likir", secondary: "Ladakh, India" },
  { main: "Saspol", secondary: "Ladakh, India" },
  { main: "Alchi", secondary: "Ladakh, India" },
  { main: "Uleytokpo", secondary: "Ladakh, India" },
  { main: "Lamayuru", secondary: "Ladakh, India" },
  { main: "Wanla", secondary: "Ladakh, India" },
  { main: "Mulbekh", secondary: "Ladakh, India" },
  { main: "Wakha", secondary: "Ladakh, India" },
  { main: "Kargil", secondary: "Ladakh, India" },
  { main: "Drass", secondary: "Ladakh, India" },
  { main: "Sonamarg", secondary: "Jammu and Kashmir, India" },
  { main: "Baltal", secondary: "Jammu and Kashmir, India" },
  { main: "Gund", secondary: "Jammu and Kashmir, India" },
  { main: "Kangan", secondary: "Jammu and Kashmir, India" },
  { main: "Ganderbal", secondary: "Jammu and Kashmir, India" },
  { main: "Srinagar", secondary: "Jammu and Kashmir, India" },
]

export function AddressAutocomplete({
  id,
  label,
  placeholder,
  value,
  onChange,
  icon,
  className = "",
}: AddressAutocompleteProps) {
  const [isOpen, setIsOpen] = useState(false)
  const [suggestions, setSuggestions] = useState<AddressSuggestion[]>([])
  const [isLoading, setIsLoading] = useState(false)

  const handleInputChange = (inputValue: string) => {
    onChange(inputValue)

    if (inputValue.length > 0) {
      setIsLoading(true)

      // Filter locations based on input
      const filtered = indiaLocations
        .filter(
          (location) =>
            location.main.toLowerCase().includes(inputValue.toLowerCase()) ||
            location.secondary.toLowerCase().includes(inputValue.toLowerCase()),
        )
        .slice(0, 8)
        .map((location, index) => ({
          place_id: `${location.main}_${index}`,
          description: `${location.main}, ${location.secondary}`,
          structured_formatting: {
            main_text: location.main,
            secondary_text: location.secondary,
          },
        }))

      setSuggestions(filtered)
      setIsOpen(filtered.length > 0)
      setIsLoading(false)
    } else {
      setSuggestions([])
      setIsOpen(false)
    }
  }

  const handleSuggestionClick = (suggestion: AddressSuggestion) => {
    onChange(suggestion.description)
    setIsOpen(false)
    setSuggestions([])
  }

  return (
    <div className={`relative ${className}`}>
      <Label htmlFor={id} className="text-sm font-medium text-gray-300 mb-2 block">
        {label}
      </Label>
      <div className="relative">
        <Input
          id={id}
          type="text"
          placeholder={placeholder}
          value={value}
          onChange={(e) => handleInputChange(e.target.value)}
          className={`border-gray-600 placeholder-gray-400 focus:border-orange-400 focus:ring-orange-400/20 ${
            value ? "bg-white text-black" : "bg-gray-800/50 text-white"
          }`}
        />

        {isLoading && (
          <div className="absolute right-3 top-1/2 transform -translate-y-1/2">
            <div className="animate-spin h-4 w-4 border-2 border-orange-400 border-t-transparent rounded-full"></div>
          </div>
        )}
      </div>

      {isOpen && suggestions.length > 0 && (
        <div className="absolute z-[9999] w-full mt-1 bg-gray-800 border border-gray-600 rounded-md shadow-lg max-h-60 overflow-auto">
          {suggestions.map((suggestion) => (
            <div
              key={suggestion.place_id}
              onClick={() => handleSuggestionClick(suggestion)}
              className="px-4 py-3 hover:bg-gray-700 cursor-pointer border-b border-gray-700 last:border-b-0"
            >
              <div className="text-white font-medium">{suggestion.structured_formatting.main_text}</div>
              <div className="text-gray-400 text-sm">{suggestion.structured_formatting.secondary_text}</div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
